### ISSUE TITLE
Update ppa

### ISSUE THREAD

**Issue by darkdragon-001** [lestcape/Nautilus-UltraCopier-Extension#2]
Please update your [ppa](https://launchpad.net/~lestcape/+archive/ubuntu/ultracopier-extensions):
* sign with latest key
* support latest Ubuntu versions

**Comment by lestcape** [comment]
The last time i see is not just the ppa, as nautilus change his internal code, it will required a change in the extension to be working with the last nautilus version. So, have not scene to me just update the ppa if will not work. For another hand, make it to work will required explored the current nautilus code, to see in first place if it's possible right now and this is a lite complicate to me. Actually i just add this, because i explored the nemo code and lucky nautilus and Nemo share the same code in the part that the extension need. This is why i just rename the name to Nautilus from Nemo. Now it's not just the name is make a complete different extension, so not.
